language: node_js
node_js:
- '7'
branches:
  only:
  - master
before_script:
- git config --global user.email "travis@devternity.com"
- git config --global user.name "Travis"
- npm install -g gulp-cli
script:
- gulp compile
- gulp deploy
env:
  global:
    secure: "tUAn3l0Y+iTiokH5w5pQPlaHpePHmhwkkDwv/3dK5PuKk1sNE0uZW/DpwSYPVKf3h6aLeXms3LS63i0M9BHUrVGpVFUNHQ0ISoDvTss8UabbI3SGX7NrJ3qBSAv7fAsbdpEK+zZBiWmwtPpGu78K0Sxu+tBpO3rpJaiGglx+rV9w+YJ+DEp9dmZMU/WRJl2+U2OpNO7/VfmmUWMs0bMdgvS2Yf/OXZjNVSmCGwqPaGX8f9O/xImGfVRdtR3Ksehvp9OajKX3pW5/fxMKcGEfm6vojoZsdNd1AxmuA8qJgmel2KdawxVfFfRvuApXsRkRWYYHYbX84XAaE+WgCfoH+HgAl94S6VNh+XhXrKl0AFJEFY8CIjGoiDQCHDUCzf/7ogV0pwQPVZ++rUrB5QQ+bWpbXc0tPOsNcEwktAYyPfdqkg5mH9y1lWJyPpjC/yZYdFCgRRqvmQ+f/19r33CRVEnCppqs5faNKJoZJsH1PKjTR+K60vStSu1zVKb43qAhVciRBmkNVcGBAcbtEFB/C25E7A/xZ4JhPKqjunk+S5qlWVTOqRR69PPuWAcTPJtWdrGvgOqhkXlaQ5g7uYAPek3tALy7xlRx2r/Pbfu6MA5d8GEKwz6TVfyEB2p+aSQL496B1ZdN4oNiXkzMd/7nfoe7qsYBhZPB4yckp4r6c08="